export interface SurahMetadata {
  id: number;
  name_ar: string;
  name_en: string;
  type: 'meccan' | 'medinan';
  ayahs: number;
}

export const SURAHS_METADATA: SurahMetadata[] = [
  { id: 1, name_ar: 'الفاتحة', name_en: 'Al-Fatihah', type: 'meccan', ayahs: 7 },
  { id: 2, name_ar: 'البقرة', name_en: 'Al-Baqarah', type: 'medinan', ayahs: 286 },
  { id: 3, name_ar: 'آل عمران', name_en: "Ali 'Imran", type: 'medinan', ayahs: 200 },
  { id: 4, name_ar: 'النساء', name_en: 'An-Nisa', type: 'medinan', ayahs: 176 },
  { id: 5, name_ar: 'المائدة', name_en: "Al-Ma'idah", type: 'medinan', ayahs: 120 },
  { id: 6, name_ar: 'الأنعام', name_en: "Al-An'am", type: 'meccan', ayahs: 165 },
  { id: 7, name_ar: 'الأعراف', name_en: "Al-A'raf", type: 'meccan', ayahs: 206 },
  { id: 8, name_ar: 'الأنفال', name_en: 'Al-Anfal', type: 'medinan', ayahs: 75 },
  { id: 9, name_ar: 'التوبة', name_en: 'At-Tawbah', type: 'medinan', ayahs: 129 },
  { id: 10, name_ar: 'يونس', name_en: 'Yunus', type: 'meccan', ayahs: 109 },
  { id: 11, name_ar: 'هود', name_en: 'Hud', type: 'meccan', ayahs: 123 },
  { id: 12, name_ar: 'يوسف', name_en: 'Yusuf', type: 'meccan', ayahs: 111 },
  { id: 13, name_ar: 'الرعد', name_en: "Ar-Ra'd", type: 'medinan', ayahs: 43 },
  { id: 14, name_ar: 'إبراهيم', name_en: 'Ibrahim', type: 'meccan', ayahs: 52 },
  { id: 15, name_ar: 'الحجر', name_en: 'Al-Hijr', type: 'meccan', ayahs: 99 },
  { id: 16, name_ar: 'النحل', name_en: 'An-Nahl', type: 'meccan', ayahs: 128 },
  { id: 17, name_ar: 'الإسراء', name_en: 'Al-Isra', type: 'meccan', ayahs: 111 },
  { id: 18, name_ar: 'الكهف', name_en: 'Al-Kahf', type: 'meccan', ayahs: 110 },
  { id: 19, name_ar: 'مريم', name_en: 'Maryam', type: 'meccan', ayahs: 98 },
  { id: 20, name_ar: 'طه', name_en: 'Ta-Ha', type: 'meccan', ayahs: 135 },
  { id: 21, name_ar: 'الأنبياء', name_en: 'Al-Anbiya', type: 'meccan', ayahs: 112 },
  { id: 22, name_ar: 'الحج', name_en: 'Al-Hajj', type: 'medinan', ayahs: 78 },
  { id: 23, name_ar: 'المؤمنون', name_en: "Al-Mu'minun", type: 'meccan', ayahs: 118 },
  { id: 24, name_ar: 'النور', name_en: 'An-Nur', type: 'medinan', ayahs: 64 },
  { id: 25, name_ar: 'الفرقان', name_en: 'Al-Furqan', type: 'meccan', ayahs: 77 },
  { id: 26, name_ar: 'الشعراء', name_en: "Ash-Shu'ara", type: 'meccan', ayahs: 227 },
  { id: 27, name_ar: 'النمل', name_en: 'An-Naml', type: 'meccan', ayahs: 93 },
  { id: 28, name_ar: 'القصص', name_en: 'Al-Qasas', type: 'meccan', ayahs: 88 },
  { id: 29, name_ar: 'العنكبوت', name_en: "Al-'Ankabut", type: 'meccan', ayahs: 69 },
  { id: 30, name_ar: 'الروم', name_en: 'Ar-Rum', type: 'meccan', ayahs: 60 },
  { id: 31, name_ar: 'لقمان', name_en: 'Luqman', type: 'meccan', ayahs: 34 },
  { id: 32, name_ar: 'السجدة', name_en: 'As-Sajdah', type: 'meccan', ayahs: 30 },
  { id: 33, name_ar: 'الأحزاب', name_en: 'Al-Ahzab', type: 'medinan', ayahs: 73 },
  { id: 34, name_ar: 'سبأ', name_en: "Saba'", type: 'meccan', ayahs: 54 },
  { id: 35, name_ar: 'فاطر', name_en: 'Fatir', type: 'meccan', ayahs: 45 },
  { id: 36, name_ar: 'يس', name_en: 'Ya-Sin', type: 'meccan', ayahs: 83 },
  { id: 37, name_ar: 'الصافات', name_en: 'As-Saffat', type: 'meccan', ayahs: 182 },
  { id: 38, name_ar: 'ص', name_en: 'Sad', type: 'meccan', ayahs: 88 },
  { id: 39, name_ar: 'الزمر', name_en: 'Az-Zumar', type: 'meccan', ayahs: 75 },
  { id: 40, name_ar: 'غافر', name_en: 'Ghafir', type: 'meccan', ayahs: 85 },
  { id: 41, name_ar: 'فصلت', name_en: 'Fussilat', type: 'meccan', ayahs: 54 },
  { id: 42, name_ar: 'الشورى', name_en: 'Ash-Shura', type: 'meccan', ayahs: 53 },
  { id: 43, name_ar: 'الزخرف', name_en: 'Az-Zukhruf', type: 'meccan', ayahs: 89 },
  { id: 44, name_ar: 'الدخان', name_en: 'Ad-Dukhan', type: 'meccan', ayahs: 59 },
  { id: 45, name_ar: 'الجاثية', name_en: 'Al-Jathiyah', type: 'meccan', ayahs: 37 },
  { id: 46, name_ar: 'الأحقاف', name_en: 'Al-Ahqaf', type: 'meccan', ayahs: 35 },
  { id: 47, name_ar: 'محمد', name_en: 'Muhammad', type: 'medinan', ayahs: 38 },
  { id: 48, name_ar: 'الفتح', name_en: 'Al-Fath', type: 'medinan', ayahs: 29 },
  { id: 49, name_ar: 'الحجرات', name_en: 'Al-Hujurat', type: 'medinan', ayahs: 18 },
  { id: 50, name_ar: 'ق', name_en: 'Qaf', type: 'meccan', ayahs: 45 },
  { id: 51, name_ar: 'الذاريات', name_en: 'Adh-Dhariyat', type: 'meccan', ayahs: 60 },
  { id: 52, name_ar: 'الطور', name_en: 'At-Tur', type: 'meccan', ayahs: 49 },
  { id: 53, name_ar: 'النجم', name_en: 'An-Najm', type: 'meccan', ayahs: 62 },
  { id: 54, name_ar: 'القمر', name_en: 'Al-Qamar', type: 'meccan', ayahs: 55 },
  { id: 55, name_ar: 'الرحمن', name_en: 'Ar-Rahman', type: 'medinan', ayahs: 78 },
  { id: 56, name_ar: 'الواقعة', name_en: "Al-Waqi'ah", type: 'meccan', ayahs: 96 },
  { id: 57, name_ar: 'الحديد', name_en: 'Al-Hadid', type: 'medinan', ayahs: 29 },
  { id: 58, name_ar: 'المجادلة', name_en: 'Al-Mujadila', type: 'medinan', ayahs: 22 },
  { id: 59, name_ar: 'الحشر', name_en: 'Al-Hashr', type: 'medinan', ayahs: 24 },
  { id: 60, name_ar: 'الممتحنة', name_en: 'Al-Mumtahanah', type: 'medinan', ayahs: 13 },
  { id: 61, name_ar: 'الصف', name_en: 'As-Saff', type: 'medinan', ayahs: 14 },
  { id: 62, name_ar: 'الجمعة', name_en: "Al-Jumu'ah", type: 'medinan', ayahs: 11 },
  { id: 63, name_ar: 'المنافقون', name_en: 'Al-Munafiqun', type: 'medinan', ayahs: 11 },
  { id: 64, name_ar: 'التغابن', name_en: 'At-Taghabun', type: 'medinan', ayahs: 18 },
  { id: 65, name_ar: 'الطلاق', name_en: 'At-Talaq', type: 'medinan', ayahs: 12 },
  { id: 66, name_ar: 'التحريم', name_en: 'At-Tahrim', type: 'medinan', ayahs: 12 },
  { id: 67, name_ar: 'الملك', name_en: 'Al-Mulk', type: 'meccan', ayahs: 30 },
  { id: 68, name_ar: 'القلم', name_en: 'Al-Qalam', type: 'meccan', ayahs: 52 },
  { id: 69, name_ar: 'الحاقة', name_en: 'Al-Haqqah', type: 'meccan', ayahs: 52 },
  { id: 70, name_ar: 'المعارج', name_en: "Al-Ma'arij", type: 'meccan', ayahs: 44 },
  { id: 71, name_ar: 'نوح', name_en: 'Nuh', type: 'meccan', ayahs: 28 },
  { id: 72, name_ar: 'الجن', name_en: 'Al-Jinn', type: 'meccan', ayahs: 28 },
  { id: 73, name_ar: 'المزمل', name_en: 'Al-Muzzammil', type: 'meccan', ayahs: 20 },
  { id: 74, name_ar: 'المدثر', name_en: 'Al-Muddaththir', type: 'meccan', ayahs: 56 },
  { id: 75, name_ar: 'القيامة', name_en: 'Al-Qiyamah', type: 'meccan', ayahs: 40 },
  { id: 76, name_ar: 'الإنسان', name_en: 'Al-Insan', type: 'medinan', ayahs: 31 },
  { id: 77, name_ar: 'المرسلات', name_en: 'Al-Mursalat', type: 'meccan', ayahs: 50 },
  { id: 78, name_ar: 'النبأ', name_en: "An-Naba'", type: 'meccan', ayahs: 40 },
  { id: 79, name_ar: 'النازعات', name_en: "An-Nazi'at", type: 'meccan', ayahs: 46 },
  { id: 80, name_ar: 'عبس', name_en: "'Abasa", type: 'meccan', ayahs: 42 },
  { id: 81, name_ar: 'التكوير', name_en: 'At-Takwir', type: 'meccan', ayahs: 29 },
  { id: 82, name_ar: 'الانفطار', name_en: 'Al-Infitar', type: 'meccan', ayahs: 19 },
  { id: 83, name_ar: 'المطففين', name_en: 'Al-Mutaffifin', type: 'meccan', ayahs: 36 },
  { id: 84, name_ar: 'الانشقاق', name_en: 'Al-Inshiqaq', type: 'meccan', ayahs: 25 },
  { id: 85, name_ar: 'البروج', name_en: 'Al-Buruj', type: 'meccan', ayahs: 22 },
  { id: 86, name_ar: 'الطارق', name_en: 'At-Tariq', type: 'meccan', ayahs: 17 },
  { id: 87, name_ar: 'الأعلى', name_en: "Al-A'la", type: 'meccan', ayahs: 19 },
  { id: 88, name_ar: 'الغاشية', name_en: 'Al-Ghashiyah', type: 'meccan', ayahs: 26 },
  { id: 89, name_ar: 'الفجر', name_en: 'Al-Fajr', type: 'meccan', ayahs: 30 },
  { id: 90, name_ar: 'البلد', name_en: 'Al-Balad', type: 'meccan', ayahs: 20 },
  { id: 91, name_ar: 'الشمس', name_en: 'Ash-Shams', type: 'meccan', ayahs: 15 },
  { id: 92, name_ar: 'الليل', name_en: 'Al-Layl', type: 'meccan', ayahs: 21 },
  { id: 93, name_ar: 'الضحى', name_en: 'Ad-Duha', type: 'meccan', ayahs: 11 },
  { id: 94, name_ar: 'الشرح', name_en: 'Ash-Sharh', type: 'meccan', ayahs: 8 },
  { id: 95, name_ar: 'التين', name_en: 'At-Tin', type: 'meccan', ayahs: 8 },
  { id: 96, name_ar: 'العلق', name_en: "Al-'Alaq", type: 'meccan', ayahs: 19 },
  { id: 97, name_ar: 'القدر', name_en: 'Al-Qadr', type: 'meccan', ayahs: 5 },
  { id: 98, name_ar: 'البينة', name_en: 'Al-Bayyinah', type: 'medinan', ayahs: 8 },
  { id: 99, name_ar: 'الزلزلة', name_en: 'Az-Zalzalah', type: 'medinan', ayahs: 8 },
  { id: 100, name_ar: 'العاديات', name_en: "Al-'Adiyat", type: 'meccan', ayahs: 11 },
  { id: 101, name_ar: 'القارعة', name_en: "Al-Qari'ah", type: 'meccan', ayahs: 11 },
  { id: 102, name_ar: 'التكاثر', name_en: 'At-Takathur', type: 'meccan', ayahs: 8 },
  { id: 103, name_ar: 'العصر', name_en: "Al-'Asr", type: 'meccan', ayahs: 3 },
  { id: 104, name_ar: 'الهمزة', name_en: 'Al-Humazah', type: 'meccan', ayahs: 9 },
  { id: 105, name_ar: 'الفيل', name_en: 'Al-Fil', type: 'meccan', ayahs: 5 },
  { id: 106, name_ar: 'قريش', name_en: 'Quraysh', type: 'meccan', ayahs: 4 },
  { id: 107, name_ar: 'الماعون', name_en: "Al-Ma'un", type: 'meccan', ayahs: 7 },
  { id: 108, name_ar: 'الكوثر', name_en: 'Al-Kawthar', type: 'meccan', ayahs: 3 },
  { id: 109, name_ar: 'الكافرون', name_en: 'Al-Kafirun', type: 'meccan', ayahs: 6 },
  { id: 110, name_ar: 'النصر', name_en: 'An-Nasr', type: 'medinan', ayahs: 3 },
  { id: 111, name_ar: 'المسد', name_en: 'Al-Masad', type: 'meccan', ayahs: 5 },
  { id: 112, name_ar: 'الإخلاص', name_en: 'Al-Ikhlas', type: 'meccan', ayahs: 4 },
  { id: 113, name_ar: 'الفلق', name_en: 'Al-Falaq', type: 'meccan', ayahs: 5 },
  { id: 114, name_ar: 'الناس', name_en: 'An-Nas', type: 'meccan', ayahs: 6 },
];

/**
 * Mapping of Juz number to its starting page in the standard 604-page Madani Mushaf.
 */
export const JUZ_PAGE_MAPPING: Record<number, number> = {
  1: 1,
  2: 22,
  3: 42,
  4: 62,
  5: 82,
  6: 102,
  7: 122,
  8: 142,
  9: 162,
  10: 182,
  11: 202,
  12: 222,
  13: 242,
  14: 262,
  15: 282,
  16: 302,
  17: 322,
  18: 342,
  19: 362,
  20: 382,
  21: 402,
  22: 422,
  23: 442,
  24: 462,
  25: 482,
  26: 502,
  27: 522,
  28: 542,
  29: 562,
  30: 582,
};
